fix: Resolved bug #115 and added test for this explicit behaviour
Safe-DS/Stdlib pull request #194
Opened 2023-04-16 18:09 UTC by Marsmaennchen221

Closes #115 .

### Summary of Changes

Fixed `table.keep_only_columns` to rearrange the column names correctly
Fixed grammar in two docs

2023-04-16 18:10 UTC, lars-reimann commented
## [🦙 MegaLinter](https://megalinter.io/6.22.1) status: ✅ [SUCCESS](https://github.com/Safe-DS/Stdlib/actions/runs/4714677915)

| Descriptor  |                                 Linter                                 |Files|Fixed|Errors|Elapsed time|
|-------------|------------------------------------------------------------------------|-----|----:|------|------------|
|✅ PYTHON    |[black](https://megalinter.io/6.22.1/descriptors/python_black)          |    2|    0|     0|0.72s       |
|✅ PYTHON    |[mypy](https://megalinter.io/6.22.1/descriptors/python_mypy)            |    2|     |     0|1.55s       |
|✅ PYTHON    |[ruff](https://megalinter.io/6.22.1/descriptors/python_ruff)            |    2|    0|     0|0.04s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6.22.1/descriptors/repository_git_diff)|yes  |     |no    |0.02s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/4714677915)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_
<!-- MegaLinter Status Report -->

<!-- megalinter: github-comment-reporter workflow='MegaLinter' jobid='lint' -->

2023-04-16 19:37 UTC, lars-reimann requested changes
The title of the PR should also be changed, so a [good changelog entry](https://stdlib.safe-ds.com/en/stable/CHANGELOG/) can be created: 

* It's not necessary to link to the issue in the title, that's what the `Closes #115` is for. 
* The title should be something that a user can understand
* It's not necessary to point out in the title that tests were added that reproduce the bug. That is implied.

It could be something like "fix: `table.keep_only_columns` now maps column names to correct data"

2023-04-16 19:37 UTC, lars-reimann commented on src/safeds/data/tabular/containers/_table.py
> +        transformed_data.columns = [self._schema.get_column_names()[i] for i in column_indices]
```suggestion
        transformed_data.columns = column_names
```

Isn't this sufficient?

2023-04-16 19:37 UTC, lars-reimann commented on tests/safeds/data/tabular/containers/_table/test_keep_only_columns.py
> +def test_keep_columns_order() -> None:
```suggestion
def test_keep_only_columns_order() -> None:
```

2023-04-16 19:37 UTC, lars-reimann commented on tests/safeds/data/tabular/containers/_table/test_keep_only_columns.py
>  def test_keep_columns_warning() -> None:
```suggestion
def test_keep_only_columns_warning() -> None:
```

2023-04-16 19:37 UTC, lars-reimann commented on tests/safeds/data/tabular/containers/_table/test_keep_only_columns.py
While we're at it, `test_keep_columns` should also be called `test_keep_only_columns` instead.

2023-04-16 19:47 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +        transformed_data.columns = [self._schema.get_column_names()[i] for i in column_indices]
yes you are right

2023-04-16 20:32 UTC, lars-reimann approved these changes
LGTM, thanks!

2023-04-16 20:32 UTC, merged

2023-04-21 08:53 UTC, lars-reimann commented
:tada: This PR is included in version 0.11.0 :tada:

The release is available on:
- `v0.11.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: