feat: Add parameter ´number_of_trees´ to ´random_forest_classifier´ and regressor
Safe-DS/Stdlib pull request #230
Opened 2023-04-21 11:28 UTC by alex-senger

Closes #161.

### Summary of Changes

Added number_of_trees parameter to initiator of random_forest_classifier and random_forest_regressor.

### Instructions for Manual Testing (if required)

2023-04-21 11:30 UTC, lars-reimann commented
## [🦙 MegaLinter](https://megalinter.io/6.22.1) status: ❌ [ERROR](https://github.com/Safe-DS/Stdlib/actions/runs/4764408615)

| Descriptor  |                                 Linter                                 |Files|Fixed|                            Errors                            |Elapsed time|
|-------------|------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------|------------|
|✅ PYTHON    |[black](https://megalinter.io/6.22.1/descriptors/python_black)          |    4|    2|                                                             0|0.6s        |
|❌ PYTHON    |[mypy](https://megalinter.io/6.22.1/descriptors/python_mypy)            |    4|     |[2](https://github.com/Safe-DS/Stdlib/actions/runs/4764408615)|1.79s       |
|❌ PYTHON    |[ruff](https://megalinter.io/6.22.1/descriptors/python_ruff)            |    4|    2|[4](https://github.com/Safe-DS/Stdlib/actions/runs/4764408615)|0.04s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6.22.1/descriptors/repository_git_diff)|yes  |     |no                                                            |0.02s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/4764408615)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_
<!-- MegaLinter Status Report -->

<!-- megalinter: github-comment-reporter workflow='MegaLinter' jobid='lint' -->

2023-04-21 13:16 UTC, PhilipGutberlet approved these changes

2023-04-21 14:35 UTC, Marsmaennchen221 requested changes

2023-04-21 14:35 UTC, Marsmaennchen221 commented on src/safeds/ml/classical/classification/_random_forest.py
> +        If the number of trees is less than 1.
```suggestion
        If the number of trees is less than or equal to 0.
```
I think it is better to understand if you use the same value in the docs (required greater than 0 -Error if less than or equal to 0)

2023-04-21 14:35 UTC, Marsmaennchen221 commented on src/safeds/ml/classical/regression/_random_forest.py
> +        If the number of trees is less than 1.
```suggestion
        If the number of trees is less than or equal to 0.
```
See Classification

2023-04-22 14:18 UTC, lars-reimann approved these changes

2023-04-22 14:18 UTC, merged

2023-05-11 20:05 UTC, lars-reimann commented
:tada: This PR is included in version 0.12.0 :tada:

The release is available on:
- `v0.12.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: