feat: add alpha parameter to `lasso_regression`
Safe-DS/Stdlib pull request #232
Opened 2023-04-21 12:39 UTC by alex-senger

Closes #163.

### Summary of Changes

Add alpha parameter to lasso regression

### Instructions for Manual Testing (if required)

2023-04-21 12:41 UTC, lars-reimann commented
## [🦙 MegaLinter](https://megalinter.io/6.22.1) status: ❌ [ERROR](https://github.com/Safe-DS/Stdlib/actions/runs/4764954869)

| Descriptor  |                                 Linter                                 |Files|Fixed|                            Errors                            |Elapsed time|
|-------------|------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------|------------|
|✅ PYTHON    |[black](https://megalinter.io/6.22.1/descriptors/python_black)          |    2|    0|                                                             0|0.56s       |
|✅ PYTHON    |[mypy](https://megalinter.io/6.22.1/descriptors/python_mypy)            |    2|     |                                                             0|1.57s       |
|❌ PYTHON    |[ruff](https://megalinter.io/6.22.1/descriptors/python_ruff)            |    2|    2|[4](https://github.com/Safe-DS/Stdlib/actions/runs/4764954869)|0.04s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6.22.1/descriptors/repository_git_diff)|yes  |     |no                                                            |0.02s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/4764954869)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_
<!-- MegaLinter Status Report -->

<!-- megalinter: github-comment-reporter workflow='MegaLinter' jobid='lint' -->

2023-04-21 12:42 UTC, alex-senger commented
Note that pytest isn't catching the warning correctly.

2023-04-22 13:19 UTC, lars-reimann requested changes

2023-04-22 13:19 UTC, lars-reimann commented on src/safeds/ml/classical/regression/_lasso_regression.py
> +            warn("alpha is zero, you should use LinearRegression instead", UserWarning, stacklevel=1)
```suggestion
            warn("Setting alpha to zero makes this model equivalent to LinearRegression. You should use LinearRegression instead for better numerical stability.", UserWarning, stacklevel=1)
```

I think this better explains why this is an issue.

2023-04-22 13:19 UTC, lars-reimann commented on src/safeds/ml/classical/regression/_lasso_regression.py
> +        Constant that multiplies the L1 term. Defaults to 1.0.
```suggestion
    alpha : float
        Controls the regularization of the model. The higher the value, the more regularized it becomes.
```

This does not rely on the mathematical definition of lasso regression as much. If we add the formular in the future, we can add your explanation again.

We usually don't need to repeat the default value here.

2023-04-28 09:50 UTC, lars-reimann requested changes

2023-04-28 09:50 UTC, lars-reimann commented on tests/safeds/ml/classical/regression/test_lasso_regression.py
> +def test_alpha_invalid() -> None:
We should also use the `test_should_` convention for these tests.

2023-04-28 11:09 UTC, lars-reimann approved these changes
LGTM, thanks!

2023-04-28 11:11 UTC, merged

2023-05-11 20:04 UTC, lars-reimann commented
:tada: This PR is included in version 0.12.0 :tada:

The release is available on:
- `v0.12.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: