Examples for column and table classes in documentation
Safe-DS/Stdlib pull request #302
Opened 2023-05-10 11:03 UTC by ilkajw

Closes #[224].

### Summary of Changes

2023-05-10 15:18 UTC, lars-reimann commented
We need to wait until [GitHub Actions is back up](https://www.githubstatus.com/). In the meantime I've merge `main` into this branch. Please check whether all functions of `Table` and `Column` are now covered by docstrings. You can also locally test whether the examples are correct by running

```
poetry run pytest --doctest-modules
```

2023-05-11 06:08 UTC, lars-reimann commented
## [🦙 MegaLinter](https://megalinter.io/6.22.2) status: ❌ [ERROR](https://github.com/Safe-DS/Stdlib/actions/runs/4944530494)

| Descriptor  |                                 Linter                                 |Files|Fixed|                            Errors                            |Elapsed time|
|-------------|------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------|------------|
|✅ PYTHON    |[black](https://megalinter.io/6.22.2/descriptors/python_black)          |    2|    1|                                                             0|1.56s       |
|✅ PYTHON    |[mypy](https://megalinter.io/6.22.2/descriptors/python_mypy)            |    2|     |                                                             0|2.24s       |
|❌ PYTHON    |[ruff](https://megalinter.io/6.22.2/descriptors/python_ruff)            |    2|    1|[9](https://github.com/Safe-DS/Stdlib/actions/runs/4944530494)|0.08s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6.22.2/descriptors/repository_git_diff)|yes  |     |no                                                            |0.03s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/4944530494)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_

<!-- megalinter: github-comment-reporter workflow='MegaLinter' jobid='lint' -->

2023-06-23 08:04 UTC, Marsmaennchen221 requested changes

2023-06-23 08:04 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +        >>> table
```suggestion
        >>> Table.from_rows([row1, row2])
```

2023-06-23 08:04 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +        >>> table
```suggestion
        >>> Table.from_columns([col1, col2])
```

2023-06-23 08:04 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +        >>> table
```suggestion
        >>> Table.from_dict(d)
```

2023-06-23 08:16 UTC, patrikguempel commented on src/safeds/data/tabular/containers/_column.py
> +        r"""
Yes, as backslashes are used within the example's return value

2023-06-23 08:16 UTC, alex-senger requested changes

2023-06-23 08:16 UTC, alex-senger commented on src/safeds/data/tabular/containers/_table.py
> +        {'temperature': [20, 25, 30], 'sales': [90, 206, 210]}
Why are you casting the slices into dicts?

2023-06-23 08:16 UTC, alex-senger commented on src/safeds/data/tabular/containers/_table.py
> +        >>> tagged_table = table.tag_columns("amount_bought")
```suggestion
        >>> tagged_table = table.tag_columns(target_name="amount_bought", feature_names=["apple", "milk", "beer"])
```

2023-06-23 08:16 UTC, alex-senger commented on src/safeds/data/tabular/containers/_table.py
> +        {'item': ['apple', 'milk', 'beer'], 'price': [100.0, 119.0, 179.0]}
Just returning the Table would be better imo.

2023-06-23 08:16 UTC, alex-senger commented on src/safeds/data/tabular/containers/_table.py
> +        2   1.0   0.0   0.0   0.0   1.0
Not a good example, as the OneHotEncoder shouldn't really be used on numerical values.

2023-06-23 11:36 UTC, Marsmaennchen221 requested changes

2023-06-23 11:36 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +        >>> new_table
```suggestion
        >>> table.remove_rows_with_outliers()
```

2023-06-23 11:36 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_column.py
> +
```suggestion
```

2023-06-23 11:36 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_column.py
> +
```suggestion
```

2023-06-23 11:36 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +
```suggestion
```

2023-06-23 11:36 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +
```suggestion
```

2023-06-23 11:36 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +
```suggestion
```

2023-06-23 11:36 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +
```suggestion
```

2023-06-23 11:36 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_table.py
> +        >>> table.sort_columns()
```suggestion
        >>> table2 = Table.from_dict({"b": [2], "a": [1]})
        >>> table2.sort_columns()
```

2023-06-23 11:40 UTC, Marsmaennchen221 submitted a review, later dismissed

2023-06-23 11:53 UTC, alex-senger approved these changes
[![LGTM](https://i.lgtm.party/VAC64N8)](https://lgtm.party/p/VAC64N8/)

2023-06-23 14:36 UTC, lars-reimann approved these changes

2023-06-23 14:38 UTC, merged

2023-06-30 07:17 UTC, lars-reimann commented
:tada: This PR is included in version 0.14.0 :tada:

The release is available on:
- `v0.14.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: