feat: flip images / eq method for image
Safe-DS/Stdlib pull request #360
Opened 2023-06-16 08:44 UTC by patrikguempel

flip images

Closes #280.

###Summary of Changes
Images can now be flipped both horizontally and vertically.
Image now has an eq method 

Co-authored-by: daniaHu <129186516+daniaHu@users.noreply.github.com>

2023-06-16 08:45 UTC, lars-reimann commented
## [🦙 MegaLinter](https://megalinter.io/7.0.4) status: ❌ [ERROR](https://github.com/Safe-DS/Stdlib/actions/runs/5288022440)

| Descriptor  |                                Linter                                 |Files|Fixed|                            Errors                            |Elapsed time|
|-------------|-----------------------------------------------------------------------|-----|----:|--------------------------------------------------------------|------------|
|✅ PYTHON    |[black](https://megalinter.io/7.0.4/descriptors/python_black)          |    2|    2|                                                             0|0.77s       |
|❌ PYTHON    |[mypy](https://megalinter.io/7.0.4/descriptors/python_mypy)            |    2|     |[7](https://github.com/Safe-DS/Stdlib/actions/runs/5288022440)|1.77s       |
|❌ PYTHON    |[ruff](https://megalinter.io/7.0.4/descriptors/python_ruff)            |    2|    2|[3](https://github.com/Safe-DS/Stdlib/actions/runs/5288022440)|0.02s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/7.0.4/descriptors/repository_git_diff)|yes  |     |no                                                            |0.01s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/5288022440)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_

<!-- megalinter: github-comment-reporter workflow='MegaLinter' jobid='lint' -->

2023-06-16 09:54 UTC, alex-senger commented on src/safeds/data/image/containers/_image.py
> +        Resize an image to any size.
```suggestion
        Return an image that has been resized to a given size.
```

2023-06-16 11:22 UTC, Marsmaennchen221 requested changes

2023-06-16 11:22 UTC, Marsmaennchen221 commented on tests/safeds/data/image/containers/test_image.py
> +    def test_should_should_be_original(self) -> None:
```suggestion
    def test_should_be_original(self) -> None:
```

2023-06-16 11:25 UTC, Marsmaennchen221 approved these changes

2023-06-16 11:25 UTC, merged

2023-06-30 07:18 UTC, lars-reimann commented
:tada: This PR is included in version 0.14.0 :tada:

The release is available on:
- `v0.14.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: