Merge remote-tracking branch 'origin/examples-for-column-and-table-cl…
Safe-DS/Stdlib pull request #386
Opened 2023-06-23 12:42 UTC by alex-senger

…asses-in-documentation' into examples-for-column-and-table-classes-in-documentation

Closes #318 

Fixes Bug:

If you use the method Table.keep_only_columns with an empty list on a table that contains at least one row, you get an empty table with a row count above 0.

### Summary of Changes

2023-06-23 12:43 UTC, lars-reimann commented
## [🦙 MegaLinter](https://megalinter.io/7.0.4) status: ✅ [SUCCESS](https://github.com/Safe-DS/Stdlib/actions/runs/5356473478)

| Descriptor  |                                Linter                                 |Files|Fixed|Errors|Elapsed time|
|-------------|-----------------------------------------------------------------------|-----|----:|------|------------|
|✅ PYTHON    |[black](https://megalinter.io/7.0.4/descriptors/python_black)          |    3|    1|     0|1.0s        |
|✅ PYTHON    |[mypy](https://megalinter.io/7.0.4/descriptors/python_mypy)            |    3|     |     0|2.26s       |
|✅ PYTHON    |[ruff](https://megalinter.io/7.0.4/descriptors/python_ruff)            |    3|    1|     0|0.03s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/7.0.4/descriptors/repository_git_diff)|yes  |     |no    |0.0s        |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Stdlib/actions/runs/5356473478)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_

<!-- megalinter: github-comment-reporter workflow='MegaLinter' jobid='lint' -->

2023-06-23 13:25 UTC, sibre28 requested changes

2023-06-23 13:25 UTC, sibre28 commented on src/safeds/data/tabular/containers/_table.py
>              return self.column_names == other.column_names
```suggestion
            return true
```
If neither Table has any columns, they are both empty tables and therefore always equals

2023-06-23 13:59 UTC, sibre28 approved these changes
[![LGTM](https://i.lgtm.party/GSQE7HO)](https://lgtm.party/p/GSQE7HO/)

2023-06-24 13:42 UTC, merged

2023-06-30 07:17 UTC, lars-reimann commented
:tada: This PR is included in version 0.14.0 :tada:

The release is available on:
- `v0.14.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: