feat: 275 add copy method for tables
Safe-DS/Stdlib pull request #405
Opened 2023-06-30 09:58 UTC by patrikguempel

Closes #275 

### Summary of Changes
Added copy method for Table, TaggedTable, Row, Column and looked through code to change usage to this method.

Co-authored-by: philipgutberlet <92990487+philipgutberlet@users.noreply.github.com>

2023-06-30 13:01 UTC, Marsmaennchen221 requested changes

2023-06-30 13:01 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_tagged_table.py
> +            A copy of the tagged table.
```suggestion
            The copy of this tagged table.
```

2023-06-30 13:01 UTC, Marsmaennchen221 commented on src/safeds/data/tabular/containers/_tagged_table.py
> +        Return a copy of the tagged table.
```suggestion
        Return a copy of this tagged table.
```

2023-06-30 13:43 UTC, PhilipGutberlet commented on tests/safeds/ml/classical/regression/test_regressor.py
> +        ids=["non-numerical data", "non-numerical-and-numerical data", "different lengths"],
```suggestion

```

2023-06-30 13:44 UTC, PhilipGutberlet commented on tests/safeds/ml/classical/regression/test_regressor.py
> +        ids=["perfect_prediction", "bad_prediction", "worst_prediction"],
```suggestion

```

2023-06-30 13:44 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_standard_scaler.py
> +        ids=["one_column"],
```suggestion

```

2023-06-30 13:44 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_standard_scaler.py
> +        id=["two_columns"],
```suggestion

```

2023-06-30 13:44 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_range_scaler.py
> +        ids=["one_column"],
```suggestion

```

2023-06-30 13:45 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_range_scaler.py
> +        ids=["one_column", "two_columns"],
```suggestion

```

2023-06-30 13:45 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_range_scaler.py
> +        ids=["one_column", "two_columns"],
```suggestion

```

2023-06-30 13:45 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_label_encoder.py
> +        ids=["no_column_names"],
```suggestion

```

2023-06-30 13:45 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_label_encoder.py
> +        ids=["no_column_names", "with_column_names"],
```suggestion

```

2023-06-30 13:45 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_imputer.py
> +            ids=["Constant", "Mean", "Median", "Mode"],
```suggestion
            ids=["Constant", "Mean", "Median", "Mode"],
```

2023-06-30 13:46 UTC, PhilipGutberlet commented on tests/safeds/data/tabular/transformation/test_imputer.py
> +            ids=["Constant", "Mean", "Median", "Mode"],
```suggestion

```

2023-06-30 13:56 UTC, Marsmaennchen221 approved these changes

2023-06-30 14:11 UTC, merged

2023-07-13 22:42 UTC, lars-reimann commented
:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- `v0.15.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: