fix: unified instances of empty table in all tests
Safe-DS/Stdlib pull request #408
Opened 2023-06-30 13:01 UTC by daniaHu

Closes #347

### Summary of Changes

Searched through tests for other forms of creating empty table than our agreed on standard "Table()", and switched them to the standard.

2023-07-06 15:56 UTC, jxnior01 requested changes
Looks good. Just a single test: `test_remove_columns_with_missing_values` needs the change.

2023-07-06 20:40 UTC, Marsmaennchen221 requested changes
Looks good so far.

You mised a few files:
_table/test_init.py
_table/test_number_of_columns.py
_table/test_number_of_rows.py
_table/test_remove_columns_with_missing_values.py

2023-07-07 13:40 UTC, patrikguempel approved these changes

2023-07-13 17:06 UTC, Marsmaennchen221 submitted a review, later dismissed
[![LGTM](https://i.lgtm.party/RR17QLA)](https://lgtm.party/p/RR17QLA/)

2023-07-13 17:23 UTC, zzril commented on tests/safeds/data/tabular/containers/_table/test_init.py
> +        (Table(), Schema({})),
The IDs suggest that this test is indeed supposed to distinguish between both cases. (Or rather, verify that both create the same table.)

2023-07-13 17:24 UTC, zzril commented on tests/safeds/data/tabular/containers/_table/test_init.py
> +        (Table(), Schema({})),
The IDs suggest that this test is indeed supposed to distinguish between both cases. (Or rather, verify that both create the same table.)

2023-07-13 17:28 UTC, zzril commented
May also consider doing the same for `Row()` vs `Row({})`.

But can also leave that for another micro-issue. :D

2023-07-13 18:15 UTC, Marsmaennchen221 commented on tests/safeds/data/tabular/containers/_table/test_init.py
> +        (Table(), Schema({})),
```suggestion
        (Table({}), Schema({})),
```
@zzril Good point 👍

2023-07-13 19:14 UTC, zzril approved these changes

2023-07-13 19:16 UTC, merged

2023-07-13 22:41 UTC, lars-reimann commented
:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- `v0.15.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: