feat: added color adjustment feature
Safe-DS/Stdlib pull request #409
Opened 2023-06-30 13:03 UTC by patrikguempel

Closes #380

### Summary of Changes
Added the color adjustment feature analogous to the previous image tasks.

2023-06-30 14:15 UTC, daniaHu submitted a review, later dismissed
[[![LGTM](https://i.lgtm.party/P6FK0QO)](https://lgtm.party/p/P6FK0QO/)](url)

2023-06-30 14:30 UTC, jxnior01 approved these changes
Nice work!

2023-07-06 20:43 UTC, Marsmaennchen221 requested changes

2023-07-06 20:43 UTC, Marsmaennchen221 commented on src/safeds/data/image/containers/_image.py
> +    def adjust_color_balance(self, factor: float) -> Image:
Please add docstrings

2023-07-07 08:34 UTC, Marsmaennchen221 requested changes

2023-07-07 08:34 UTC, Marsmaennchen221 commented on src/safeds/data/image/containers/_image.py
> +        The new, adjusted image.
```suggestion
        image: Image
            The new, adjusted image.
```

2023-07-07 08:34 UTC, Marsmaennchen221 approved these changes

2023-07-07 17:11 UTC, merged

2023-07-13 22:41 UTC, lars-reimann commented
:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- `v0.15.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: