fix: added the missing ids in parameterized tests
Safe-DS/Stdlib pull request #412
Opened 2023-06-30 14:04 UTC by PhilipGutberlet

Closes #362 

### Summary of Changes

Some parameterized tests didn't have ids. The missing ids are added now.

2023-06-30 14:21 UTC, jxnior01 commented on tests/safeds/data/tabular/transformation/test_standard_scaler.py
> +        ids=["two columns"],
```suggestion
        ids=["two_columns"],
```

2023-06-30 14:21 UTC, jxnior01 commented on tests/safeds/data/tabular/transformation/test_standard_scaler.py
> +        ids=["one column"],
```suggestion
        ids=["one_column"],
```

2023-06-30 14:25 UTC, daniaHu commented
There are a couple functions, where ids are missing in test_image.py

2023-06-30 14:47 UTC, Marsmaennchen221 commented
@PhilipGutberlet please add the "Time spent by team" for your Issue

2023-07-06 20:54 UTC, Marsmaennchen221 requested changes
Looks good so far.

You missed the following tests:
`test_should_raise_if_index_out_of_bounds` in _table/test_slice_rows.py
`test_should_return_sorted_table` in _table/test_sort_rows.py
`test_should_not_modify_original_table` in _table/test_sort_rows.py
`test_should_return_dict_for_table` in _table/test_to_dict.py
`test_should_raise_if_column_not_found` in _table/test_transform_table.py

You also missed tests in the tests for Image

2023-07-07 11:56 UTC, Marsmaennchen221 submitted a review, later dismissed

2023-07-07 13:26 UTC, Marsmaennchen221 approved these changes

2023-07-07 13:26 UTC, merged

2023-07-13 22:41 UTC, lars-reimann commented
:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- `v0.15.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: