Standardize optional type in docstrings
Safe-DS/Stdlib pull request #420
Opened 2023-07-05 21:56 UTC by jxnior01

Closes #374 

### Summary of Changes

* Selected `optional type` and standardized it in docstrings

Co-authored-by: PhilipGutberlet <92990487+PhilipGutberlet@users.noreply.github.com>

2023-07-06 20:16 UTC, Marsmaennchen221 commented
Didn´t we say we want the docs to be the same as the implementation so we don´t want `Optional[...]` and we do want `... | None` in the implementation as well as in the docstrings?

2023-07-06 20:19 UTC, Marsmaennchen221 requested changes

2023-07-06 20:19 UTC, Marsmaennchen221 commented on docs/development/guidelines.md
> +
```suggestion
    ```

```

2023-07-06 20:19 UTC, Marsmaennchen221 commented on docs/development/guidelines.md
> +
```suggestion
    ```
```

2023-07-07 12:01 UTC, Marsmaennchen221 requested changes

2023-07-07 12:39 UTC, alex-senger requested changes
There is still an "optional docstring" in `InvertibleTableTransformer.fit()` in `_table_transformer.py`

2023-07-07 14:35 UTC, alex-senger approved these changes
[![LGTM](https://i.lgtm.party/1N7T2VRO)](https://lgtm.party/p/1N7T2VRO/)

2023-07-11 13:21 UTC, Marsmaennchen221 requested changes
Looks good so far.

You missed the docstrings in method `Table.slice_rows`

In `regression.AddaBoost` please change the docstring for `AdaBoost.learner` to return a `Regressor`

2023-07-13 12:19 UTC, jxnior01 commented
> > Looks good so far.
> > You missed the docstrings in method `Table.slice_rows`
> > In `regression.AddaBoost` please change the docstring for `AdaBoost.learner` to return a `Regressor`
> 
> Adressed these issues. Also merged current `main` into this.

Thanks. I'm rounding up with issue #150. I planned resolving all reviews when i'm done.

2023-07-13 17:08 UTC, Marsmaennchen221 approved these changes
[![LGTM](https://i.lgtm.party/2MISV3O)](https://lgtm.party/p/2MISV3O/)

2023-07-13 19:05 UTC, merged

2023-07-13 22:41 UTC, lars-reimann commented
:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- `v0.15.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: