docs: Sort __all__ list guideline instruction
Safe-DS/Stdlib pull request #433
Opened 2023-07-07 08:37 UTC by PhilipGutberlet

Closes #370

### Summary of Changes

Sorted the entries in `__all__` list in `__init__.py` files and added an instruction to the guidelines.

2023-07-07 09:23 UTC, zzril commented
Just on a side note: For updating the guidelines, this will already be addressed by another PR, see [this](https://github.com/Safe-DS/Stdlib/issues/370#issuecomment-1624257780) comment, so it was not really necessary to change it.

2023-07-07 09:28 UTC, zzril commented on docs/development/guidelines.md
> +The exceptions in the `__all__` list in `src/safeds/exceptions/__init__.py` should be sorted alphabetically. This makes it easier for users to find the exception they are looking for.
```suggestion
The exceptions in the `__all__` list in `src/safeds/exceptions/__init__.py` should be sorted alphabetically. This helps to reduce the likelihood of merge conflicts when new exceptions are introduced on different branches.
```

2023-07-07 11:17 UTC, lars-reimann commented on docs/development/guidelines.md
> +The exceptions in the `__all__` list in `src/safeds/exceptions/__init__.py` should be sorted alphabetically. This makes it easier for users to find the exception they are looking for.
```suggestion
### Sort the entries in the `__all__` list alphabetically

The entires in the `__all__` list in `__init__.py` files should be sorted alphabetically. This makes it easier for users to find the exception they are looking for.
```

2023-07-07 13:32 UTC, PhilipGutberlet commented on docs/development/guidelines.md
> +The exceptions in the `__all__` list in `src/safeds/exceptions/__init__.py` should be sorted alphabetically. This makes it easier for users to find the exception they are looking for.
applied

2023-07-07 13:32 UTC, robmeth approved these changes

2023-07-07 13:51 UTC, patrikguempel submitted a review, later dismissed

2023-07-07 17:16 UTC, lars-reimann requested changes

2023-07-07 17:16 UTC, lars-reimann commented on docs/development/guidelines.md
> +    __all__ =[
```suggestion
    __all__ = [
```

2023-07-07 17:16 UTC, lars-reimann commented on docs/development/guidelines.md
> +    __all__ =[
```suggestion
    __all__ = [
```

2023-07-07 17:26 UTC, lars-reimann approved these changes

2023-07-07 17:31 UTC, merged

2023-07-13 22:42 UTC, lars-reimann commented
:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- `v0.15.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: