docs: Created a Regression Getting Started Tutorial
Safe-DS/Stdlib pull request #437
Opened 2023-07-07 13:22 UTC by PhilipGutberlet

Closes #400

### Summary of Changes

Created a Regression Getting Started Tutorial and added it together with the Classification Getting Started Tutorial to the docs.

2023-07-07 14:14 UTC, alex-senger requested changes

2023-07-07 14:14 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "feature_columns = set(train_table.column_names)-set([\"price\",\"id\"])\n",
```suggestion
    "feature_columns = set(train_table.column_names) - set([\"price\",\"id\"])\n",
```

2023-07-07 14:14 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "tagged_train_table= train_table.tag_columns(\"price\", feature_names=[\n",
```suggestion
    "tagged_train_table = train_table.tag_columns(\"price\", feature_names=[\n",
```

2023-07-07 14:14 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "pricing.slice_rows(1,15)"
Add comment saying that we slice the rows for overview purposes.

2023-07-07 14:14 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "\n",
```suggestion
```

2023-07-07 14:14 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "fitted_model = model.fit(tagged_train_table)\n"
```suggestion
    "fitted_model = model.fit(tagged_train_table)"
```

2023-07-07 14:14 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "    *feature_columns\n",
```suggestion
    "    *feature_columns",
```

2023-07-07 14:14 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "test_table = testing_table.remove_columns([\"price\"])\n"
```suggestion
    "test_table = testing_table.remove_columns([\"price\"])"
```

2023-07-07 14:14 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "fitted_model.mean_absolute_error(tagged_test_table)\n"
```suggestion
    "fitted_model.mean_absolute_error(tagged_test_table)"
```

2023-07-07 14:17 UTC, lars-reimann commented on docs/tutorials/getting_started_regression.ipynb
For the calls of `slice_rows` I'd suggest to also include the first row (`slice_rows(0, 15)` or `slice_rows(end=15)`).

2023-07-07 14:19 UTC, lars-reimann commented on docs/tutorials/getting_started_classification.ipynb
Likewise, when creating the test set, it makes sense to shuffle the rows first.

2023-07-07 14:19 UTC, lars-reimann commented on docs/tutorials/getting_started_regression.ipynb
Likewise, when creating the test set, it makes sense to shuffle the rows first.

2023-07-07 14:37 UTC, alex-senger requested changes

2023-07-07 14:37 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "#For visualisation purposes we only print out the first 15 rows.\n",
```suggestion
    "# For visualisation purposes we only print out the first 15 rows.\n",
```

2023-07-07 14:37 UTC, alex-senger commented on docs/tutorials/getting_started_regression.ipynb
> +    "#For visualisation purposes we only print out the first 15 rows.\n",
```suggestion
    "# For visualisation purposes we only print out the first 15 rows.\n",
```

2023-07-07 14:39 UTC, alex-senger submitted a review, later dismissed
[![LGTM](https://i.lgtm.party/978HG1SG)](https://lgtm.party/p/978HG1SG/)

2023-07-07 17:36 UTC, jxnior01 submitted a review, later dismissed
Nicee!!

2023-07-11 13:47 UTC, Marsmaennchen221 requested changes

2023-07-11 13:47 UTC, Marsmaennchen221 commented on docs/tutorials/getting_started_classification.ipynb
> +   }
```suggestion
   }
```

2023-07-13 19:40 UTC, zzril commented
Not sure about the sorting of the tutorials (the `Data Processing` seems simpler to me and should possibly be first).

But can make a new issue for that.

2023-07-13 19:42 UTC, zzril requested changes
The numbering in the notebook seems off.

After `3. Tag the price Column as the target variable to be predicted. Use the new names of the fitted Columns as features, which will be used to make predictions based on the target variable.` follows `6. Use Decision Tree regressor as a model for the regression. Pass the "tagged_pricing" table to the fit function of the model:`.

2023-07-13 19:52 UTC, Marsmaennchen221 commented
> Not sure about the sorting of the tutorials (the `Data Processing` seems simpler to me and should possibly be first).
> 
> But can make a new issue for that.

I agree. I am also not sure about the "Getting started" in the title. All tutorials right now are some kind of a "Getting started" tutorial so I think we should just remove this prefix and rearrange the tutorials. We can do this in this pr

2023-07-13 19:55 UTC, Marsmaennchen221 commented
> Also, the code cell after `3.` looks strange:
> 
> ```python
> feature_columns = set(train_table.column_names) - set(["price", "id"])
> 
> tagged_train_table = train_table.tag_columns("price", feature_names=[
>     *feature_columns])
> ```
> 
> What's up with the `*`?
The `*` lists all the values in the given set so the list does not get one variable as set but gets all the values from the set as different variables:
```py
a = set(["a", "b", "c"])
print(a)
print([a])
print([*a])

"""
Output:
{'b', 'c', 'a'}
[{'b', 'c', 'a'}]
['b', 'c', 'a']
"""
```

2023-07-13 19:56 UTC, Marsmaennchen221 commented on docs/tutorials/getting_started_regression.ipynb
> +    "6. Use `Decision Tree` regressor as a model for the regression. Pass the \"tagged_pricing\" table to the fit function of the model:\n"
```suggestion
    "4. Use `Decision Tree` regressor as a model for the regression. Pass the \"tagged_pricing\" table to the fit function of the model:\n"
```

2023-07-13 19:56 UTC, Marsmaennchen221 commented on docs/tutorials/getting_started_regression.ipynb
> +    "7. Use the fitted decision tree regression model, that we trained on the training dataset to predict the price of a house in the test dataset.\n"
```suggestion
    "5. Use the fitted decision tree regression model, that we trained on the training dataset to predict the price of a house in the test dataset.\n"
```

2023-07-13 19:56 UTC, Marsmaennchen221 commented on docs/tutorials/getting_started_regression.ipynb
> +    "7. You can test the mean absolute error of that model with the initial testing_table as follows:\n"
```suggestion
    "6. You can test the mean absolute error of that model with the initial testing_table as follows:\n"
```

2023-07-13 19:57 UTC, zzril commented
> The `*` lists all the values in the given set so the list does not get one variable as set but gets all the values from the set as different variables

Ok, thanks for the clarification.

2023-07-13 19:57 UTC, Marsmaennchen221 commented
> The numbering in the notebook seems off.
> 
> After `3. Tag the price Column as the target variable to be predicted. Use the new names of the fitted Columns as features, which will be used to make predictions based on the target variable.` follows `6. Use Decision Tree regressor as a model for the regression. Pass the "tagged_pricing" table to the fit function of the model:`.

Done

2023-07-13 20:01 UTC, zzril commented
> > Not sure about the sorting of the tutorials (the `Data Processing` seems simpler to me and should possibly be first).
> > But can make a new issue for that.
> 
> I agree. I am also not sure about the "Getting started" in the title. All tutorials right now are some kind of a "Getting started" tutorial so I think we should just remove this prefix and rearrange the tutorials. We can do this in this pr

Makes sense.

Need to remember to update the reference in `mkdocs.yml` then,

2023-07-13 20:01 UTC, jxnior01 approved these changes

2023-07-13 20:24 UTC, zzril commented
Nice, thanks.

Let me check the page in the browser really quick...

2023-07-13 20:27 UTC, zzril commented
`Classification` also has a counting error (7 follows 7). :D

2023-07-13 20:29 UTC, Marsmaennchen221 commented on docs/tutorials/classification.ipynb
> +    "7. You can test the accuracy of that model with the initial testing_table as follows:"
```suggestion
    "8. You can test the accuracy of that model with the initial testing_table as follows:"
```

2023-07-13 20:30 UTC, zzril approved these changes
[![LGTM](https://i.lgtm.party/16637JCD)](https://lgtm.party/p/16637JCD/)

2023-07-13 20:34 UTC, merged

2023-07-13 22:40 UTC, lars-reimann commented
:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- `v0.15.0`
- [GitHub release](https://github.com/Safe-DS/Stdlib/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: